// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1alpha2/services/check-in.proto

/*
Package services is a generated protocol buffer package.

It is generated from these files:
	v1alpha2/services/check-in.proto
	v1alpha2/services/faq.proto

It has these top-level messages:
	GetCheckInRequest
	GetFaqRequest
*/
package services

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import v1alpha2_types "github.com/andrewhowdencom/mtm-apis/pkg/go/v1alpha2/types"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Takes a subset of the fields of "CheckIn"
type GetCheckInRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *GetCheckInRequest) Reset()                    { *m = GetCheckInRequest{} }
func (m *GetCheckInRequest) String() string            { return proto.CompactTextString(m) }
func (*GetCheckInRequest) ProtoMessage()               {}
func (*GetCheckInRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetCheckInRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func init() {
	proto.RegisterType((*GetCheckInRequest)(nil), "v1alpha2.services.GetCheckInRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CheckInService service

type CheckInServiceClient interface {
	GetCheckIn(ctx context.Context, in *GetCheckInRequest, opts ...grpc.CallOption) (*v1alpha2_types.CheckIn, error)
	PutCheckIn(ctx context.Context, in *v1alpha2_types.CheckIn, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type checkInServiceClient struct {
	cc *grpc.ClientConn
}

func NewCheckInServiceClient(cc *grpc.ClientConn) CheckInServiceClient {
	return &checkInServiceClient{cc}
}

func (c *checkInServiceClient) GetCheckIn(ctx context.Context, in *GetCheckInRequest, opts ...grpc.CallOption) (*v1alpha2_types.CheckIn, error) {
	out := new(v1alpha2_types.CheckIn)
	err := grpc.Invoke(ctx, "/v1alpha2.services.CheckInService/GetCheckIn", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *checkInServiceClient) PutCheckIn(ctx context.Context, in *v1alpha2_types.CheckIn, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/v1alpha2.services.CheckInService/PutCheckIn", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CheckInService service

type CheckInServiceServer interface {
	GetCheckIn(context.Context, *GetCheckInRequest) (*v1alpha2_types.CheckIn, error)
	PutCheckIn(context.Context, *v1alpha2_types.CheckIn) (*google_protobuf.Empty, error)
}

func RegisterCheckInServiceServer(s *grpc.Server, srv CheckInServiceServer) {
	s.RegisterService(&_CheckInService_serviceDesc, srv)
}

func _CheckInService_GetCheckIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckInServiceServer).GetCheckIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha2.services.CheckInService/GetCheckIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckInServiceServer).GetCheckIn(ctx, req.(*GetCheckInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CheckInService_PutCheckIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1alpha2_types.CheckIn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckInServiceServer).PutCheckIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1alpha2.services.CheckInService/PutCheckIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckInServiceServer).PutCheckIn(ctx, req.(*v1alpha2_types.CheckIn))
	}
	return interceptor(ctx, in, info, handler)
}

var _CheckInService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1alpha2.services.CheckInService",
	HandlerType: (*CheckInServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCheckIn",
			Handler:    _CheckInService_GetCheckIn_Handler,
		},
		{
			MethodName: "PutCheckIn",
			Handler:    _CheckInService_PutCheckIn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1alpha2/services/check-in.proto",
}

func init() { proto.RegisterFile("v1alpha2/services/check-in.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x25, 0xdf, 0xa2, 0x1f, 0xce, 0x42, 0xe8, 0x2c, 0x8c, 0xc4, 0x56, 0x4a, 0xe8, 0x42, 0xc4,
	0xce, 0xc5, 0xba, 0x13, 0x71, 0xa1, 0x88, 0x74, 0x27, 0x75, 0x27, 0x82, 0x4c, 0x92, 0x6b, 0x32,
	0xb4, 0x99, 0x99, 0x66, 0x26, 0x2d, 0x45, 0xdc, 0xf8, 0x0a, 0x3e, 0x9a, 0x4f, 0x20, 0xf8, 0x20,
	0x92, 0xdf, 0x2e, 0x82, 0xcb, 0xc3, 0x39, 0x73, 0x7e, 0xee, 0x90, 0xd1, 0xfa, 0x9c, 0x2f, 0x75,
	0xc2, 0xa7, 0x60, 0x30, 0x5b, 0x8b, 0x10, 0x0d, 0x84, 0x09, 0x86, 0x8b, 0x89, 0x90, 0x4c, 0x67,
	0xca, 0x2a, 0xda, 0x6f, 0x14, 0xac, 0x51, 0x78, 0xc3, 0xf6, 0x91, 0xdd, 0xea, 0xce, 0x0b, 0xef,
	0x28, 0x56, 0x2a, 0x5e, 0x22, 0x94, 0x28, 0xc8, 0x5f, 0x01, 0x53, 0x6d, 0xb7, 0x35, 0x39, 0xa8,
	0x49, 0xae, 0x05, 0x70, 0x29, 0x95, 0xe5, 0x56, 0x28, 0x69, 0x2a, 0xd6, 0x3f, 0x23, 0xfd, 0x7b,
	0xb4, 0xb7, 0x85, 0xdf, 0x4c, 0xce, 0x71, 0x95, 0xa3, 0xb1, 0xd4, 0x25, 0xff, 0x73, 0x83, 0xd9,
	0x8b, 0x88, 0x0e, 0x9d, 0x91, 0x73, 0xb2, 0x37, 0xef, 0x15, 0x70, 0x16, 0x4d, 0xbf, 0x1d, 0xb2,
	0x5f, 0x6b, 0x1f, 0xab, 0x6e, 0x74, 0x45, 0xc8, 0xce, 0x80, 0x8e, 0x59, 0xa7, 0x3c, 0xeb, 0xf8,
	0x7b, 0xee, 0x4e, 0x55, 0xee, 0x61, 0x35, 0xef, 0x8f, 0x3f, 0xbe, 0x7e, 0x3e, 0xff, 0x1d, 0xd3,
	0x01, 0xb4, 0x83, 0x9b, 0xa9, 0xf0, 0x56, 0x57, 0x7a, 0xa7, 0xcf, 0x84, 0x3c, 0xe4, 0x6d, 0xe4,
	0x5f, 0x66, 0xde, 0x01, 0xab, 0x96, 0xb3, 0xe6, 0x2c, 0xec, 0xae, 0x38, 0x8b, 0x3f, 0x2c, 0x43,
	0x5c, 0x8f, 0x76, 0x43, 0x2e, 0x9d, 0xd3, 0x9b, 0xeb, 0xa7, 0xab, 0x58, 0xd8, 0x24, 0x0f, 0x58,
	0xa8, 0x52, 0xe0, 0x32, 0xca, 0x70, 0x93, 0xa8, 0x4d, 0x84, 0xb2, 0xc0, 0xa9, 0x4d, 0x27, 0x5c,
	0x0b, 0x03, 0x7a, 0x11, 0x43, 0xac, 0xa0, 0xf3, 0x9b, 0x41, 0xaf, 0x8c, 0xbb, 0xf8, 0x0d, 0x00,
	0x00, 0xff, 0xff, 0x20, 0x06, 0xaf, 0x0f, 0xe9, 0x01, 0x00, 0x00,
}
