// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1alpha2/types/faq.proto

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	v1alpha2/types/faq.proto

It has these top-level messages:
	Faq
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// FAQ represents a frequently asked question of some kind
type Faq struct {
	// Should be a UUID (https://en.wikipedia.org/wiki/Universally_unique_identifier)
	// Example: e1da1be2-eff2-11e8-a204-0f0dc88152cb
	FaqId string `protobuf:"bytes,1,opt,name=faq_id,json=faqId" json:"faq_id,omitempty"`
	// Should be an english tag based on the IETF lanaguag tag system, delimited by an underscore.
	//
	// Examples:
	//   - en_AU
	//   - en_GB
	//   - asf_AU
	//
	// See:
	//   - http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
	//   - https://stackoverflow.com/a/3191726/3897856
	//   - https://www.w3.org/International/articles/language-tags/
	Language string `protobuf:"bytes,2,opt,name=language" json:"language,omitempty"`
	// Should be a fully formed question including punctuation that indicates it's a question
	// Example: "What is the date today?"
	Question string `protobuf:"bytes,3,opt,name=question" json:"question,omitempty"`
	// Should be an answer to the question defined in the field called "question"
	// Example: "It's Thursday, 46th of Noly, 2024"
	Answer string `protobuf:"bytes,4,opt,name=answer" json:"answer,omitempty"`
}

func (m *Faq) Reset()                    { *m = Faq{} }
func (m *Faq) String() string            { return proto.CompactTextString(m) }
func (*Faq) ProtoMessage()               {}
func (*Faq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Faq) GetFaqId() string {
	if m != nil {
		return m.FaqId
	}
	return ""
}

func (m *Faq) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Faq) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

func (m *Faq) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

func init() {
	proto.RegisterType((*Faq)(nil), "v1alpha2.types.Faq")
}

func init() { proto.RegisterFile("v1alpha2/types/faq.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xcf, 0x3d, 0xab, 0xc2, 0x30,
	0x18, 0x40, 0x61, 0x7a, 0x7b, 0x2d, 0x9a, 0xc1, 0x21, 0xa0, 0x04, 0x27, 0x71, 0x72, 0xb1, 0x41,
	0x9d, 0xc4, 0xcd, 0x41, 0x70, 0x75, 0x74, 0x91, 0xb7, 0x26, 0x4d, 0x83, 0x6d, 0x3e, 0x9a, 0xd4,
	0xe2, 0xbf, 0x97, 0x46, 0x2b, 0x38, 0x1e, 0x9e, 0xe9, 0x20, 0xf2, 0x58, 0x43, 0x69, 0x0a, 0xd8,
	0x50, 0xff, 0x34, 0xdc, 0xd1, 0x1c, 0x6c, 0x6a, 0x6a, 0xed, 0x35, 0x1e, 0xf7, 0x92, 0x06, 0x59,
	0x94, 0x28, 0x3e, 0x82, 0xc5, 0x13, 0x94, 0xe4, 0x60, 0xaf, 0x92, 0x91, 0x68, 0x1e, 0x2d, 0x47,
	0xe7, 0x41, 0x0e, 0xf6, 0xc4, 0xf0, 0x0c, 0x0d, 0x4b, 0x50, 0xa2, 0x01, 0xc1, 0xc9, 0x5f, 0x80,
	0x6f, 0x77, 0x66, 0x1b, 0xee, 0xbc, 0xd4, 0x8a, 0xc4, 0x6f, 0xeb, 0x1b, 0x4f, 0x51, 0x02, 0xca,
	0xb5, 0xbc, 0x26, 0xff, 0x41, 0x3e, 0x75, 0xd8, 0x5f, 0x76, 0x42, 0xfa, 0xa2, 0xc9, 0xd2, 0x9b,
	0xae, 0x28, 0x28, 0x56, 0xf3, 0xb6, 0xd0, 0x2d, 0xe3, 0xaa, 0xeb, 0xca, 0x57, 0x2b, 0x30, 0xd2,
	0x51, 0x73, 0x17, 0x54, 0x68, 0xfa, 0x3b, 0x91, 0x25, 0xe1, 0x60, 0xfb, 0x0a, 0x00, 0x00, 0xff,
	0xff, 0x94, 0x55, 0x73, 0x71, 0xdd, 0x00, 0x00, 0x00,
}
